name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}
      PORT: ${{ vars.PORT }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - run: npm test
      - run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npm run test:e2e
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message), '#skip') == false}}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message), '#skip') == false}}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  success_notification:
    needs: [build_and_test, deploy]
    if: ${{ success() && github.event_name == 'push' && contains(join(github.event.commits.*.message), '#skip') == false}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Discord notification success
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: ':white_check_mark: Successful deplyment!'
          title: 'Show details'
          url: ${{ github.event.head_commit.url }}
          description: |
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
  fail_notification:
    needs: [build_and_test, deploy]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Discord notification fail
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          FAILED_JOB: ${{ case(
            needs.build_and_test.result == 'failure', 'build_and_test' ,
            needs.deploy.result == 'failure', 'deploy',
            'unknown'
            )}}
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: ':x: Build failed!'
          title: 'Details'
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ env.BRANCH_NAME }}
            **Commit:** ${{ github.sha }}
            **Author:** ${{ github.actor }}
            **Workflow:** ${{ github.workflow }}
            **Job:** ${{ env.FAILED_JOB }}

            [View workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [View commit](${{ github.server_url }}/${{ github.repository }}/commit/${{github.event.after}})
